#ifndef CONFIG_H_
#define CONFIG_H_




#define LCD_IO_1ST_PORT_LETTER D
#define LCD_IO_2ND_PORT_LETTER E



#define PORT_LETTER_TO_DD(PORT_LETTER)  _PORT_LETTER_TO_DD(PORT_LETTER)
#define _PORT_LETTER_TO_DD(PORT_LETTER)  DDR ## PORT_LETTER

#define PORT_LETTER_TO_PORT(PORT_LETTER)  _PORT_LETTER_TO_PORT(PORT_LETTER)
#define _PORT_LETTER_TO_PORT(PORT_LETTER)  PORT ## PORT_LETTER

#define PORT_LETTER_TO_PIN(PORT_LETTER)  _PORT_LETTER_TO_PIN(PORT_LETTER)
#define _PORT_LETTER_TO_PIN(PORT_LETTER)  PIN ## PORT_LETTER

#endif /* CONFIG_H_ */
