/*
 * Config.h
 *
 * Created: 21/09/2020 17:11:31
 *  Author: 230712
 */ 


#ifndef CONFIG_H_
#define CONFIG_H_

#define LCD_IO_CMD_PORT_LETTER A
#define LCD_IO_CMD_PORT_RS 0
#define LCD_IO_CMD_PORT_RW 1
#define LCD_IO_CMD_PORT_EN 2
#define LCD_IO_DATA_PORT_LETTER B
#define KEYPAD_PORT_LETTER D

#define INPUT_MODE 0x00
#define OUTPUT_MODE 0xFF

#define ALL_BITS 0xFF
#define CLEAR_BITS 0x00


#define PORT_LETTER_TO_DD(PORT_LETTER)  _PORT_LETTER_TO_DD(PORT_LETTER)
#define _PORT_LETTER_TO_DD(PORT_LETTER)  DDR ## PORT_LETTER

#define PORT_LETTER_TO_PORT(PORT_LETTER)  _PORT_LETTER_TO_PORT(PORT_LETTER)
#define _PORT_LETTER_TO_PORT(PORT_LETTER)  PORT ## PORT_LETTER

#define PORT_LETTER_TO_PIN(PORT_LETTER)  _PORT_LETTER_TO_PIN(PORT_LETTER)
#define _PORT_LETTER_TO_PIN(PORT_LETTER)  PIN ## PORT_LETTER




#endif /* CONFIG_H_ */
